config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  get  '/signup',  to: 'vendors#new'
  resources :vendors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
   validates :password, confirmation: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  def new
  	@vendor = Vendor.new
  end

  def create
  	@vendor = Vendor.new(vendor_params)
  	if @vendor.save
  		redirect_to @vendor, notice: 'User was successfully created!' 
  	else
  		# render :text => "here"
  		render action: "new"	
	end	
 	end

	def show
		@vendor = Vendor.find(params[:id])
	end

	private 
		def vendor_params
				params.require(:vendor).permit(:name, :email, :password,:password_confirmation,:poc,:phone,:address, :city,:zip, :website, :picture)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# def format_phone(phone, mobile=false)
 #    return phone if format.blank?
 #    groupings = format.scan(/d+/).map { |g| g.length }
 #    groupings = [3, 3, 4] unless groupings.length == 3
 #    ActionController::Base.helpers.number_to_phone(
 #      phone,
 #      :area_code => format.index('(') ? true : false,
 #      :groupings => groupings,
 #      :delimiter => format.reverse.match(/[^d]/).to_s
 #    )
 #  end
end

app/helpers/vendor_helper.rb
module VendorHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <div class="wrapper">
  <head>

    <title>Party.me - Everthing you need for a party</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js'></script>
	<script type="text/javascript" src="../assets/index.js"></script>
    <link href="../assets/style.css" rel='stylesheet' type='text/css' />
		<div class="header">
		<div class="container">
		
			<div class="logo">
				<h1>PARTY.ME</h1>
				<span>Everthing you need for a party</span>
			</div>
			</div>
</div>

  </head>
  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

    <%= yield %>
  
  </body>
</div>
</html>

app/views/vendors/new.html.erb
<!DOCTYPE html>
<html>
<head>
<!-- for-mobile-apps -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta property="og:title" content="Vide" />
<meta name="keywords" content="Big store Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //for-mobile-apps -->
<link href="../assets/bootstrap.css" rel='stylesheet' type='text/css' />
<!-- Custom Theme files -->
<link href="../assets/style.css" rel='stylesheet' type='text/css' />
<!-- js -->
   <script src="../assets/jquery-1.11.1.min.js"></script>
<!-- //js -->
<!-- start-smoth-scrolling -->
<script type="text/javascript" src="../assets/move-top.js"></script>
<script type="text/javascript" src="../assets/easing.js"></script>
<script type="text/javascript" src="../assets/index.js"></script>
<script> 
  jQuery(function($){
    $("#appointment_phone").mask("(999) 999-9999");
  });
</script>
<!-- 
<script type="text/javascript">
	jQuery(document).ready(function($) {
		$(".scroll").click(function(event){		
			event.preventDefault();
			$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
		});
	});
</script> -->
<!-- start-smoth-scrolling -->
<link href="../assets/font-awesome.css" rel="stylesheet"> 
<link href='//fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Noto+Sans:400,700' rel='stylesheet' type='text/css'>
<body>
<% provide(:title, 'Sign up') %>

<div class="row">

  <div class="col-md-6 col-md-offset-3">
  <center><h1>Sign up</h1></center>

    <%= form_for(@vendor) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :poc %>
      <%= f.text_field :poc %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.label :phone %>
      <%= f.phone_field :phone %>
 
      <%= f.label :address %>
      <%= f.text_field :address %>

      <%= f.label :city %>
      <%= f.text_field :city %>

      <%= f.label :zip %>
      <%= f.text_field :zip %>

      <%= f.label :website %>
      <%= f.text_field :website %>

      <%= f.label :picture %>
      <%= f.file_field :picture %>



      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
</body>
</html>

app/views/vendors/show.html.erb
<!DOCTYPE html>
<html>
<head>
<!-- for-mobile-apps -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta property="og:title" content="Vide" />
<meta name="keywords" content="Big store Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //for-mobile-apps -->
<link href="../assets/bootstrap.css" rel='stylesheet' type='text/css' />
<!-- Custom Theme files -->
<link href="../assets/style.css" rel='stylesheet' type='text/css' />
<!-- js -->
   <script src="../assets/jquery-1.11.1.min.js"></script>
<!-- //js -->
<!-- start-smoth-scrolling -->
<script type="text/javascript" src="../assets/move-top.js"></script>
<script type="text/javascript" src="../assets/easing.js"></script>

<!-- 
<script type="text/javascript">
	jQuery(document).ready(function($) {
		$(".scroll").click(function(event){		
			event.preventDefault();
			$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
		});
	});
</script> -->
<!-- start-smoth-scrolling -->
<link href="../assets/font-awesome.css" rel="stylesheet"> 
<link href='//fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Noto+Sans:400,700' rel='stylesheet' type='text/css'>
<body>
<% provide(:title, 'Vendor dashboard') %>

<div class="row">

  <div class="col-md-6 col-md-offset-3">
  <center><h1>Dashboard</h1></center>
  <table>
    <tr>
      <td><%= @vendor.name %></td>
      <td><%= @vendor.email %></td>
      
      <!-- <td><%= link_to 'Show', vendor_path(@vendor) %></td> -->
    </tr>
</table>
  </div>
</div>
</body>
</html>